jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[development]
    - name: Lint with black
      run: black --check --verbose .
    - name: Lint with flake8
      run: flake8 --count --statistics
    - name: Test with pytest
      run: pytest
    strategy:
      matrix:
        os: [macOS-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
name: Test
on: [pull_request, push]
